### ISSUE TITLE
Share to single activityType

### ISSUE THREAD

**Issue by grEvenX** [leecrossley/cordova-plugin-social-message#22]
Lovely plugin. This is a feature request if you have your own interface for sharing to a specific medium.
E.g. if you in your app have "Twitter" or "Facebook" buttons to share to one or the other, it is possible (at least in the iOS SDK, don't know about Android) to fire up the share dialog instead of going through the "selection" first.
Please let me know if there's any chance that this can be implemented in your plugin.

In iOS this is accomplished with a code like:

```
    serviceType = SLServiceTypeFacebook;

    SLComposeViewController *viewController = [SLComposeViewController composeViewControllerForServiceType:serviceType];
    [viewController setInitialText:@"Text to share"];
    [viewController addURL:[NSURL URLWithString:@"http://example.com"]];

    viewController.completionHandler = ^(SLComposeViewControllerResult result){
        // TODO: if iOS < 7, dismiss SLComposeViewController manually because of different 

       // return some results to cordova here...

    };

    [[UIApplication sharedApplication].keyWindow.rootViewController presentModalViewController:viewController animated:YES];
```

**Comment by ghost** [comment]
@leecrossley, is it possible to use it already, and may I also ask you if it's possible to check if the activity type is available with cordova api? Than you!

**Comment by ghost** [comment]
I mean the account for activity type is configured and could be used by the app

**Comment by grEvenX** [comment]
This project is probably not usable and maintained any longer, closing this issue.
