### ISSUE TITLE
Crash with iPad and iOS 8 

### ISSUE THREAD

**Issue by 0sm3l** [leecrossley/cordova-plugin-social-message#31]
Hello!

I was testing an app with the iPad Simulator and iOS 8 and as soon as the social message code gets executed I get a crash. It only happens with the iPad and iOS 8 combination though, it seems to work fine on iPhone / iOS 8, and iPad iOS 7. Can anyone take a look at it to see what's going on?

(Cordova 3.4.0)

Thanks!

2014-10-22 15:51:42.173 FI[11166:161408] THREAD WARNING: ['SocialMessage'] took '110.743896' ms. Plugin should use a background thread.
2014-10-22 15:51:42.178 FI[11166:161408] Assuming sourceView is not nil
2014-10-22 15:51:47.186 FI[11166:161408] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<_UIAlertControllerActionSheetRegularPresentationController: 0x7f981d54bee0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001062c13f5 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001097adbb7 objc_exception_throw + 45
	2   UIKit                               0x0000000106dc704f -[UIPopoverPresentationController presentationTransitionWillBegin] + 2650
	3   UIKit                               0x00000001067b18c7 __71-[UIPresentationController _initViewHierarchyForPresentationSuperview:]_block_invoke + 1398
	4   UIKit                               0x00000001067b0366 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 175
	5   UIKit                               0x00000001066d0461 _applyBlockToCFArrayCopiedToStack + 314
	6   UIKit                               0x00000001066d02db _afterCACommitHandler + 516
	7   CoreFoundation                      0x00000001061f6347 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	8   CoreFoundation                      0x00000001061f62a0 __CFRunLoopDoObservers + 368
	9   CoreFoundation                      0x00000001061ec0d3 __CFRunLoopRun + 1123
	10  CoreFoundation                      0x00000001061eba06 CFRunLoopRunSpecific + 470
	11  GraphicsServices                    0x000000010af529f0 GSEventRunModal + 161
	12  UIKit                               0x00000001066ad550 UIApplicationMain + 1282
	13  FI                        0x0000000105f89907 main + 71
	14  libdyld.dylib                       0x0000000109f09145 start + 1
	15  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by emint88** [comment]
on which file I should use above code ?

**Comment by 0sm3l** [comment]
SocialMessage.m

**Comment by manfromshadow** [comment]
Confirmed

**Comment by leecrossley** [comment]
Can someone please PR the fix, @0sm3l?

**Comment by NomadDevs** [comment]
seems to still crash ipads on 9.1, any fix?

**Comment by kimuraeiji214** [comment]
I have this problem also. Can anyone help ?

**Comment by NomadDevs** [comment]
I switched to this, seems to work with everything (if you dont pass an image, just a link or text): https://www.npmjs.com/package/cordova-plugin-x-socialsharing
