### ISSUE TITLE
TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by manojakondi** [leecrossley/cordova-plugin-social-message#39]
I was trying to create a basic share option in my app which I'm trying on ionic framework. I'm getting this below error in console upon clicking share.

    TypeError: Cannot read property 'send' of undefined

This is the code that I've used to implement share. Can you tell where I'm going wrong.

    $scope.share = function($index){
            window.socialmessage.send({
                url: $scope.blogs[$index].URL
            });
        }

**Comment by leecrossley** [comment]
It will either be a problem with your angular implementation or you have not waited for the deviceready event to be fired
