### ISSUE TITLE
window.socialmessage undefined

### ISSUE THREAD

**Issue by leandrolimasi** [leecrossley/cordova-plugin-social-message#40]
I get a error undefined in use with cordova 5.1.1 and Jquery mobile.

Any help?

**Comment by leecrossley** [comment]
https://github.com/leecrossley/cordova-plugin-social-message/blob/80754a441972122f945b0ce3199170ca2ff2602a/README.md#usage

Ensure you use the plugin after your deviceready event has been fired.

**Comment by leandrolimasi** [comment]
Hi,

I'm use the "window.socialmessage" in the click of the button. I believe that is a after deviceready, because the is render and the user click in any time after.

**Comment by leecrossley** [comment]
You'll be setting up the event before `deviceready`... sorry, but this is an issue with your implementation and not an issue with the plugin
