### ISSUE TITLE
it's not issue but a question

### ISSUE THREAD

**Issue by ibrahimmumcu** [leecrossley/cordova-plugin-social-message#45]
I'm trying to make this plugin work with my dynamic data. So this is my code: 

```
$http({
        method: 'POST',
        url: 'http://www.xxx.com/api/yazi.php'
    }).success(function(data, status) {
        $scope.yazi = data;
    }).error(function(data, status) {
        console.log('get movie request failed! data: ' + data);
    });

    $scope.share = function(){
        var message = {
            text: $scope.yazi.post_title,
            image: $scope.yazi.image_url,
            url: $scope.yazi.guid
        };
        $window.socialmessage.send(message);
    };
```

It's getting data and binding to $scope in order to use in view side.. That's normal angular implementation. But this is not working.  

But If I use like this it's working:

```
var message = {
    text: "Image test",
    image: "http://cordova.apache.org/images/cordova_bot.png"
};
```

It shouldn't be a problem If I use the plugin with dynamic data, right?
Is there any suggestion?
Thanks.

**Comment by leecrossley** [comment]
Yes, it will work with dynamic data. The only help I can offer is that you check your `$scope.yazi` object at the time the message is created, what happens if you console.log...

```
    $scope.share = function(){
        console.log($scope.yazi); // what does this show?
        var message = {
            text: $scope.yazi.post_title,
            image: $scope.yazi.image_url,
            url: $scope.yazi.guid
        };
...
```

**Comment by ibrahimmumcu** [comment]
Ok I found the problem. It's working but so slow. The size of image that I've point as $scope.yazi.image_url is like 400 KB. I think that's why it's working slow. What do you think?
